theme: jekyll-theme-midnight
# Site navigation links
- title: Home
  url: /
  # Site navigation links
- title: media
  url: /media/

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Beth Tellman
  avatar: #
  bio: #
  email: et2663[at]columbia.edu
  # Do not include the @ symbol in your Twitter username
  twitter: pazjusticiavida
  linkedin: #username
  github: beth-tellman
  orcid: 0000-0003-3026-6435
  researchgate: #username
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: #id
  facebook: #username
  instagram: #username
  bing-verify:
  stackoverflow: #123456/username from a "https://stackoverflow.com/users/123456/username" link
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname:
